server:
  port: 8090
security:
  user:
    name: markus
    password: Hhw9JU90uQLp5s5WudFE 

redmine:
  issues:
    link: http://redmine.lifeline-herne.de/issues/
  protocol:
    name: Protokoll
    mandatory:
      - Nummer
      - Anwesend
      - Essen
      - Ort
      - Moderation
      - Andacht
    fields:
      number: Nummer
      members: Anwesend
      meal: Essen
      location: Ort
      moderation: Moderation
      devotion: Andacht
    closed: Erledigt
