# Example configuration
# ATTENTION! DO NOT COMMIT THE RESULTING FILE TO PUBLIC GITHUB REPOSITORY!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/<database name>
    username: <database username>
    password: <database password>
    testOnBorrow: true
    validationQuery: SELECT 1
  mail:
    password: <mail password>
  security:
    user:
      name: <basic auth name>
      password: <basic auth password>
redmine:
  api:
    accesskey: <redmine api accesskey>