server:
  port: 8090

redmine:
  protocol:
    name: Protokoll
    mandatory:
      - Nummer
      - Anwesend
      - Essen
      - Ort
      - Moderation
      - Andacht
    fields:
      number: Nummer
      members: Anwesend
      meal: Essen
      location: Ort
      moderation: Moderation
      devotion: Andacht
    closed: Erledigt
