server:
  port: 8090

redmine:
  protocol:
    name: Protokoll
    mandatory:
      - Nummer
      - Anwesend
      - Essen
      - Ort
      - Moderation
      - Andacht
    number: Nummer
    closed: Erledigt
