server:
  port: 8090
security:
  user:
    name: markus
    password: Hhw9JU90uQLp5s5WudFE 

redmine:
  issues:
    link: http://redmine.lifeline-herne.de/issues/
  protocol:
    name: Protokoll
    mandatory:
      - Nummer
      - Anwesend
      - Essen
      - Ort
      - Moderation
      - Andacht
    fields:
      number: Nummer
      members: Anwesend
      meal: Essen
      location: Ort
      moderation: Moderation
      devotion: Andacht
    closed: Erledigt
  mail:
    recipient: markus.d.meier@gmail.com
    host: gmail.com
    subject: Protokoll vom Gemeinderat am %s
    body: Hallo lieber Gemeinderat,<br/><br/>hier das Protokoll von unserer Sitzung am %s.<br/><br/>Vielen Dank für eure Mitarbeit!<br/><br/>Liebe Grüße,<br/>Euer Markus