server:
  port: 8090
spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 465
    username: markus.d.meier@gmail.com
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.debug: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
logging:
  file: redmine.protocol.log

redmine:
  api:
    url: http://redmine.lifeline-herne.de/
  issues:
    link: http://redmine.lifeline-herne.de/issues/
  protocol:
    name: Protokoll
    closed: Erledigt
    mandatory:
    - Nummer
    - Anwesend
    - Essen
    - Ort
    - Moderation
    - Andacht
    members:
    - Alberto
    - Ann
    - Anne
    - Markus
    - Paul
    - Stefan
    fields:
      number: Nummer
      participants: Anwesend
      meal: Essen
      location: Ort
      moderation: Moderation
      devotion: Andacht
    switches:
      printLastNameInitial: false
  mail:
    recipients:
    - mail.example.com
    subject: Protokoll vom Gemeinderat am %s
    body: Hallo lieber Gemeinderat,<br/><br/>anbei das Protokoll von unserer Sitzung am %s.<br/>Es kann auch online eingesehen werden unter %s.<br/><br/>Vielen Dank für eure Mitarbeit!<br/><br/>Liebe Grüße,<br/>Euer Markus