server:
  port: 8090
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://host:port/database
    username: username
    password: password

redmine:
  api:
    url: url
    accesskey: accesskey
  protocol:
    name: Protokoll
    mandatory:
      - Nummer
      - Anwesend
      - Essen
      - Ort
      - Moderation
      - Andacht
    number: Nummer
    closed: Erledigt
